alias sdq="ssh root@dqv-build"
alias sv1="ssh root@ychvm1"
alias sv2="ssh root@ychvm2"
alias sv3="ssh root@ychvm3"
alias sv4="ssh ychvm4"
alias sdn="ssh devnas"
alias sbu="ssh root@build"
alias ssb="ssh root@superbuild"
